# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Ellesa Sabasaje | UX Designer & Strategist"
email: "uxellesa@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  "Holistic digital product designer with a knack for UX design, UX strategy, UX research, prototyping and front-end development"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emsky.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "skyellesa"
github_username:  "emsky"

# Build settings
markdown:
  kramdown:
    input: GFM

sass:
    sass_dir: _sass

source: .
destination: _site

collections:
  redirects:
    output: true
    permalink: /:path/

plugins:
  - markdownify

newline: >
  :

# Folders to process
permalink: /posts/:title.html
//relative_permalinks: false # Fixes problem with relative links not working
include:
    - "_work"
    - .htaccess
exclude:
    - .DS_Store
    - .gitignore
    - config.codekit3
    - "_work/_templat"
    - Gemfile
    - Gemfile.lock
    - README.md
